"""Alembic environment.

The database URL always comes from application settings so migrations and the
API can never disagree about which database they target.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from app.core.config import get_settings
from app.core.errors import ConfigurationError
from app.db import models  # noqa: F401 - registers the entities on Base.metadata
from app.db.base import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def include_object(
    obj: object, name: str | None, type_: str, reflected: bool, compare_to: object
) -> bool:
    """Keep objects this application does not own out of autogenerated migrations.

    The PostGIS image ships entire families of its own tables (spatial_ref_sys,
    the tiger geocoder). Without this filter, autogenerate would happily emit
    ``drop_table`` for every one of them.
    """
    del obj
    if reflected and compare_to is None:
        return False
    # GeoAlchemy2 creates the spatial index itself when the column is created.
    return not (type_ == "index" and name is not None and name.startswith("idx_"))


def _database_url() -> str:
    url = get_settings().database_url
    if not url:
        msg = "SENTINEL_DATABASE_URL is required to run migrations"
        raise ConfigurationError(msg, details={"setting": "SENTINEL_DATABASE_URL"})
    return url


def run_migrations_offline() -> None:
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = _database_url()

    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
